#

ffplay:
  ffplay udp://192.168.1.3:5000

gst:
  gst-launch-0.10 -vvv playbin uri=file:///home/mavlab/paparazzi/sw/ext/ardrone2_vision/ardrone2_gstreamer/sdp/x86_config-mp4.sdp

cvlc:
  cvlc file:///home/mavlab/paparazzi/sw/ext/ardrone2_vision/ardrone2_gstreamer/sdp/x86_config-h264.sdp

